<!-- Tufts VUE 3.2.2 concept-map (evidence and assay-all.vue) 2015-04-13 -->
<!-- Tufts VUE: http://vue.tufts.edu/ -->
<!-- Do Not Remove: VUE mapping @version(1.1) jar:file:/C:/Program%20Files%20(x86)/VUE/VUE.jar!/tufts/vue/resources/lw_mapping_1_1.xml -->
<!-- Do Not Remove: Saved date Mon Apr 13 22:49:45 CDT 2015 by yuln on platform Windows 8 6.2 in JVM 1.7.0_21-b11 -->
<!-- Do Not Remove: Saving version @(#)VUE: built May 23 2013 at 2146 by tomadm on Linux 2.6.18-348.2.1.el5 i386 JVM 1.7.0_21-b11(bits=32) -->
<?xml version="1.0" encoding="US-ASCII"?>
<LW-MAP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="none" ID="0"
    label="evidence and assay-all.vue" created="1428592062148" x="0.0"
    y="0.0" width="1.4E-45" height="1.4E-45" strokeWidth="0.0" autoSized="false">
    <resource referenceCreated="1428983396957" size="100819"
        spec="C:\Users\yuln\Dropbox\miragingdb\modeling\evidence and assay-all.vue"
        type="1" xsi:type="URLResource">
        <title>evidence and assay-all.vue</title>
        <property key="File" value="C:\Users\yuln\Dropbox\miragingdb\modeling\evidence and assay-all.vue"/>
    </resource>
    <fillColor>#FFFFFF</fillColor>
    <strokeColor>#404040</strokeColor>
    <textColor>#000000</textColor>
    <font>SansSerif-plain-14</font>
    <URIString>http://vue.tufts.edu/rdf/resource/9ed8cde4c0a80007011f218416565db8</URIString>
    <child ID="79" layerID="1" created="1428637566752" x="-66.96118"
        y="415.75" width="58.46118" height="36.75" strokeWidth="1.0"
        autoSized="false" controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#EA2218</strokeColor>
        <textColor>#EA2218</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a187dd4fc0a80007011f218415c17f79</URIString>
        <point1 x="-9.0" y="452.0"/>
        <point2 x="-66.46118" y="416.25"/>
        <ID2 xsi:type="node">78</ID2>
    </child>
    <child ID="53"
        label="conclusion based on &#xa;data generated by asay"
        layerID="1" created="1428635834988" x="0.5" y="406.75"
        width="116.0" height="38.0" strokeWidth="1.0" autoSized="false"
        controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#EA2218</strokeColor>
        <textColor>#EA2218</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a1643450c0a80007011f2184d84d3a51</URIString>
        <point1 x="59.733334" y="444.25"/>
        <point2 x="57.266666" y="407.25"/>
        <ID1 xsi:type="node">46</ID1>
        <ID2 xsi:type="node">52</ID2>
    </child>
    <child ID="7"
        label="biology assay:&#xa;western blot&#xa;Northen blotting&#xa;Luciferase assays&#xa;real time PCR&#xa;RT-PCR&#xa;Flow cytometry analysis&#xa;... "
        layerID="1" created="1428592129515" x="347.0" y="-109.0"
        width="140.0" height="128.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#ECFFD4</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cde6c0a80007011f2184a411d2d0</URIString>
        <shape arcwidth="20.0" archeight="20.0" xsi:type="roundRect"/>
    </child>
    <child ID="8" label="miRNA target protein&#xa;emperical conclusion"
        layerID="1" created="1428592163282" x="352.0" y="65.0"
        width="129.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cde7c0a80007011f21843dbd4039</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="9" label="anatomic part:&#xa;cell &#xa;tissue&#xa;organ"
        layerID="1" created="1428593128286" x="558.5" y="-78.75"
        width="102.0" height="68.0" strokeWidth="1.0" autoSized="false" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cde7c0a80007011f2184ef252b18</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="10"
        label="biological process:&#xa;miRNA expression;&#xa;traget protein expression;&#xa;miRNA traget gene mRNA binding"
        layerID="1" created="1428593151758" x="510.5" y="34.5"
        width="198.0" height="71.875" strokeWidth="1.0"
        autoSized="false" xsi:type="node">
        <fillColor>#ECFFD4</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cde8c0a80007011f218493f3ad53</URIString>
        <shape arcwidth="20.0" archeight="20.0" xsi:type="roundRect"/>
    </child>
    <child ID="11" label="occurs in" layerID="1" created="1428593174956"
        x="587.0" y="-11.25" width="45.0" height="46.25"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cde8c0a80007011f218407af943c</URIString>
        <point1 x="609.5" y="34.5"/>
        <point2 x="609.5" y="-10.75"/>
        <ID1 xsi:type="node">10</ID1>
        <ID2 xsi:type="node">9</ID2>
    </child>
    <child ID="12" label="organism" layerID="1" created="1428593187926"
        x="722.0" y="21.25" width="64.0" height="23.0" strokeWidth="1.0"
        autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdeac0a80007011f2184391af33c</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="13" label="part of" layerID="1" created="1428593202507"
        x="660.0" y="-17.897064" width="73.058044" height="39.647064"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdeac0a80007011f2184876eec61</URIString>
        <point1 x="660.5" y="-17.397064"/>
        <point2 x="732.55804" y="21.25"/>
        <ID1 xsi:type="node">9</ID1>
        <ID2 xsi:type="node">12</ID2>
    </child>
    <child ID="14" label="study model role" layerID="1"
        created="1428593245965" x="722.0" y="-39.875" width="102.0"
        height="25.0" strokeWidth="1.0" autoSized="false" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdebc0a80007011f218463883ae9</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="15" label="has role" layerID="1" created="1428593258076"
        x="743.84204" y="-15.375" width="39.0" height="37.125"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdebc0a80007011f21846a93475d</URIString>
        <point1 x="757.6341" y="21.25"/>
        <point2 x="769.0499" y="-14.875"/>
        <ID1 xsi:type="node">12</ID1>
        <ID2 xsi:type="node">14</ID2>
    </child>
    <child ID="16" label="disease " layerID="1" created="1428593301493"
        x="722.0" y="72.125" width="59.0" height="23.0"
        strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdecc0a80007011f2184b82af84c</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="20" label="has disposition" layerID="1"
        created="1428593415823" x="716.75" y="43.75" width="72.0"
        height="28.875" strokeWidth="1.0" autoSized="false"
        controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdf3c0a80007011f2184729902bb</URIString>
        <point1 x="753.4349" y="44.25"/>
        <point2 x="752.0651" y="72.125"/>
        <ID1 xsi:type="node">12</ID1>
        <ID2 xsi:type="node">16</ID2>
    </child>
    <child ID="21" label="aging process&#xa;GO:0021700" layerID="1"
        created="1428593477657" x="845.5" y="-30.625" width="90.0"
        height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#ECFFD4</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdf4c0a80007011f21846e91a6e3</URIString>
        <shape arcwidth="20.0" archeight="20.0" xsi:type="roundRect"/>
    </child>
    <child ID="23" label="participates in" layerID="1"
        created="1428593548416" x="783.0525" y="1.9823303" width="67.0"
        height="20.864746" strokeWidth="1.0" autoSized="false"
        controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdf5c0a80007011f21849fc251a6</URIString>
        <point1 x="786.0" y="22.347076"/>
        <point2 x="847.105" y="2.4823303"/>
        <ID1 xsi:type="node">12</ID1>
        <ID2 xsi:type="node">21</ID2>
    </child>
    <child ID="24" label="aged quality" layerID="1"
        created="1428593570144" x="852.0" y="21.25" width="77.0"
        height="23.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdf6c0a80007011f2184b5532674</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="25" label="has quality" layerID="1"
        created="1428593654429" x="785.5" y="25.75" width="67.0"
        height="14.0" strokeWidth="1.0" autoSized="false"
        controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdf6c0a80007011f218462213175</URIString>
        <point1 x="786.0" y="32.75"/>
        <point2 x="852.0" y="32.75"/>
        <ID1 xsi:type="node">12</ID1>
        <ID2 xsi:type="node">24</ID2>
    </child>
    <child ID="26"
        label="miR-29 is upregulated in &#xa;Zmpste24 -/- progeroid mice "
        layerID="1" created="1428593774087" x="-127.0" y="301.5"
        width="170.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdf6c0a80007011f2184e9f43006</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="28" label="is_a" layerID="1" created="1428593809627"
        x="-112.895164" y="277.0" width="40.290314" height="25.0"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdf7c0a80007011f218402d11806</URIString>
        <point1 x="-73.10485" y="301.5"/>
        <point2 x="-112.395164" y="277.5"/>
        <ID1 xsi:type="node">26</ID1>
        <ID2 xsi:type="node">89</ID2>
    </child>
    <child ID="29" label="bead-based flow&#xa;cytometry platform"
        layerID="1" created="1428593846661" x="-30.0" y="200.0"
        width="110.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#ECFFD4</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdf8c0a80007011f21840f54e4c1</URIString>
        <shape arcwidth="20.0" archeight="20.0" xsi:type="roundRect"/>
    </child>
    <child ID="30" label="biology assay" layerID="1"
        created="1428593879710" x="-175.0" y="207.5" width="91.0"
        height="23.0" strokeWidth="1.0" autoSized="false" xsi:type="node">
        <fillColor>#ECFFD4</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdf8c0a80007011f2184eea2d718</URIString>
        <shape arcwidth="20.0" archeight="20.0" xsi:type="roundRect"/>
    </child>
    <child ID="31" label="is_a" layerID="1" created="1428593885276"
        x="-84.5" y="212.0" width="55.0" height="14.0" strokeWidth="1.0"
        autoSized="false" controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdf9c0a80007011f2184b0200aaa</URIString>
        <point1 x="-30.0" y="219.0"/>
        <point2 x="-84.0" y="219.0"/>
        <ID1 xsi:type="node">29</ID1>
        <ID2 xsi:type="node">30</ID2>
    </child>
    <child ID="32"
        label="conclusion based on data&#xa;generated by asay"
        layerID="1" created="1428593901226" x="-71.0" y="237.5"
        width="125.0" height="64.5" strokeWidth="1.0" autoSized="false"
        controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#EA2218</strokeColor>
        <textColor>#EA2218</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdf9c0a80007011f2184d8ece8e1</URIString>
        <point1 x="-29.458126" y="301.5"/>
        <point2 x="12.45813" y="238.0"/>
        <ID1 xsi:type="node">26</ID1>
        <ID2 xsi:type="node">29</ID2>
    </child>
    <child ID="33" label="Zmpste24 -/- mouse" layerID="1"
        created="1428593935308" x="292.0" y="263.0" width="123.0"
        height="23.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdfac0a80007011f218402f63452</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="34" label="study model role" layerID="1"
        created="1428593985619" x="302.5" y="206.5" width="102.0"
        height="23.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdfac0a80007011f2184a7238fa3</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="35" label="has role" layerID="1" created="1428593994515"
        x="334.0" y="229.0" width="39.0" height="34.5" strokeWidth="1.0"
        autoSized="false" controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdfbc0a80007011f2184c130c01f</URIString>
        <point1 x="353.5" y="263.0"/>
        <point2 x="353.5" y="229.5"/>
        <ID1 xsi:type="node">33</ID1>
        <ID2 xsi:type="node">34</ID2>
    </child>
    <child ID="36" label="liver of &#xa;Zmpste24 -/-mouse" layerID="1"
        created="1428594008275" x="158.0" y="199.5" width="120.0"
        height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdfbc0a80007011f218439132ef2</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="37" label="part of" layerID="1" created="1428594016587"
        x="263.47324" y="237.0" width="62.700867" height="26.5"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdfbc0a80007011f21841a2d9dfc</URIString>
        <point1 x="263.97324" y="237.5"/>
        <point2 x="325.6741" y="263.0"/>
        <ID1 xsi:type="node">36</ID1>
        <ID2 xsi:type="node">33</ID2>
    </child>
    <child ID="38" label="Hutchinson&#x2013;Gilford progeria"
        layerID="1" created="1428594027442" x="251.5" y="315.0"
        width="166.0" height="24.5" strokeWidth="1.0" autoSized="false" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdfdc0a80007011f2184bf4e1b8e</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="39" label="has disposition" layerID="1"
        created="1428594058123" x="308.13507" y="285.5" width="72.0"
        height="29.999939" strokeWidth="1.0" autoSized="false"
        controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdfdc0a80007011f218415128993</URIString>
        <point1 x="349.35782" y="286.0"/>
        <point2 x="338.91235" y="314.99994"/>
        <ID1 xsi:type="node">33</ID1>
        <ID2 xsi:type="node">38</ID2>
    </child>
    <child ID="40" label="has&#xa; evaluant" layerID="1"
        created="1428596218566" x="79.5" y="204.75647" width="79.0"
        height="28.0" strokeWidth="1.0" autoSized="false"
        controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#EA2218</strokeColor>
        <textColor>#EA2218</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9f00dd5cc0a80007011f21841927c212</URIString>
        <point1 x="80.0" y="218.85751"/>
        <point2 x="158.0" y="218.65544"/>
        <ID1 xsi:type="node">29</ID1>
        <ID2 xsi:type="node">36</ID2>
    </child>
    <child ID="41" label="miR-29 expression" layerID="1"
        created="1428596335878" x="100.0" y="269.5" width="116.0"
        height="23.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#ECFFD4</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9f00dd5dc0a80007011f2184f648bf94</URIString>
        <shape arcwidth="20.0" archeight="20.0" xsi:type="roundRect"/>
    </child>
    <child ID="42" label="output data&#xa; is about" layerID="1"
        created="1428596413787" x="65.25806" y="237.5" width="68.57261"
        height="32.5" strokeWidth="1.0" autoSized="false"
        controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#EA2218</strokeColor>
        <textColor>#EA2218</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9f00dd5dc0a80007011f218476ca83c4</URIString>
        <point1 x="65.75805" y="238.0"/>
        <point2 x="133.33066" y="269.5"/>
        <ID1 xsi:type="node">29</ID1>
        <ID2 xsi:type="node">41</ID2>
    </child>
    <child ID="43" label="occurs in" layerID="1" created="1428596486373"
        x="161.9" y="237.0" width="45.0" height="33.0" strokeWidth="1.0"
        autoSized="false" controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9f00dd5dc0a80007011f2184522df35f</URIString>
        <point1 x="169.04" y="269.5"/>
        <point2 x="199.76001" y="237.5"/>
        <ID1 xsi:type="node">41</ID1>
        <ID2 xsi:type="node">36</ID2>
    </child>
    <child ID="44" label="publication 21522133 " layerID="1"
        created="1428596575948" x="88.5" y="316.5" width="133.0"
        height="23.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9f00dd5ec0a80007011f218434ded502</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="45" label="part of" layerID="1" created="1428596610346"
        x="42.5" y="317.60217" width="46.5" height="14.0"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/9f00dd5ec0a80007011f218498a46466</URIString>
        <point1 x="43.0" y="323.73605"/>
        <point2 x="88.5" y="325.4683"/>
        <ID1 xsi:type="node">26</ID1>
        <ID2 xsi:type="node">44</ID2>
    </child>
    <child ID="46" label="TNF increases miR-31&#xa;in human HDFs"
        layerID="1" created="1428635311920" x="-7.0" y="444.25"
        width="136.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a164344fc0a80007011f218487d946a9</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="47" label="is about" layerID="1" created="1428635374807"
        x="42.499996" y="290.53333" width="63.573677" height="14.0"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#000000</strokeColor>
        <textColor>#4C4C4C</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a164344fc0a80007011f2184bb1ed834</URIString>
        <point1 x="43.0" y="303.7125"/>
        <point2 x="105.57368" y="291.3542"/>
        <ID1 xsi:type="node">26</ID1>
        <ID2 xsi:type="node">41</ID2>
    </child>
    <child ID="48" label="publication 19949084" layerID="1"
        created="1428635426331" x="59.0" y="509.625" width="130.0"
        height="23.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a164344fc0a80007011f218471f53a99</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="49" label="part of" layerID="1" created="1428635446489"
        x="80.58206" y="481.75" width="32.0" height="28.375"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a164344fc0a80007011f218497dff6f6</URIString>
        <point1 x="81.682495" y="482.25"/>
        <point2 x="111.48163" y="509.625"/>
        <ID1 xsi:type="node">46</ID1>
        <ID2 xsi:type="node">48</ID2>
    </child>
    <child ID="50"
        label="upregulated&#xa;miRNA expression &#xa;conclusion"
        layerID="1" created="1428635462102" x="-91.5" y="500.625"
        width="117.0" height="53.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a164344fc0a80007011f2184cf2a79c6</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="51" label="is_a" layerID="1" created="1428635471233"
        x="5.4980545" y="481.75" width="28.041096" height="19.375"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a1643450c0a80007011f2184d5753257</URIString>
        <point1 x="33.03915" y="482.25"/>
        <point2 x="5.9980555" y="500.625"/>
        <ID1 xsi:type="node">46</ID1>
        <ID2 xsi:type="node">50</ID2>
    </child>
    <child ID="52"
        label="mircoRNA profiling assay &#xa;by array assay (OBI_0001335)"
        layerID="1" created="1428635481089" x="-32.0" y="369.25"
        width="176.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#ECFFD4</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a1643450c0a80007011f21847053bb14</URIString>
        <shape arcwidth="20.0" archeight="20.0" xsi:type="roundRect"/>
    </child>
    <child ID="55" label="human dermal&#xa; fibroblasts (HDFs)"
        layerID="1" created="1428635891932" x="225.0" y="369.25"
        width="115.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a1643450c0a80007011f2184dd508410</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="57" label="has&#xa; evaluant" layerID="1"
        created="1428635918939" x="143.5" y="374.25" width="82.0"
        height="28.0" strokeWidth="1.0" autoSized="false"
        controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#EA2218</strokeColor>
        <textColor>#EA2218</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a1643450c0a80007011f21849000fe83</URIString>
        <point1 x="144.0" y="388.25"/>
        <point2 x="225.0" y="388.25"/>
        <ID1 xsi:type="node">52</ID1>
        <ID2 xsi:type="node">55</ID2>
    </child>
    <child ID="58" label="human " layerID="1" created="1428636000794"
        x="304.5" y="445.25" width="53.0" height="23.0"
        strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a1643450c0a80007011f21840d73b2dd</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="65" label="part of" layerID="1" created="1428636435124"
        x="293.4051" y="406.75" width="32.0" height="39.00003"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a1643450c0a80007011f21843429e44c</URIString>
        <point1 x="295.95255" y="407.25"/>
        <point2 x="322.85767" y="445.25003"/>
        <ID1 xsi:type="node">55</ID1>
        <ID2 xsi:type="node">58</ID2>
    </child>
    <child ID="68" label="has disposition" layerID="1"
        created="1428636554778" x="295.24146" y="467.75" width="72.0"
        height="38.125" strokeWidth="1.0" autoSized="false"
        controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#4C4C4C</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a1643451c0a80007011f21842b319a06</URIString>
        <point1 x="331.09238" y="468.25"/>
        <point2 x="331.39056" y="505.375"/>
        <ID1 xsi:type="node">58</ID1>
        <ID2 xsi:type="node">69</ID2>
    </child>
    <child ID="69" label="inflammation" layerID="1"
        created="1428636563595" x="290.0" y="505.375" width="83.0"
        height="27.25" strokeWidth="1.0" autoSized="false" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a1643451c0a80007011f218466b7baee</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="70" label="miR-31 expression" layerID="1"
        created="1428636634722" x="178.0" y="445.25" width="116.0"
        height="23.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#ECFFD4</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a1643451c0a80007011f21847783c23f</URIString>
        <shape arcwidth="20.0" archeight="20.0" xsi:type="roundRect"/>
    </child>
    <child ID="71" label="output data&#xa; is about" layerID="1"
        created="1428636644657" x="105.42697" y="406.75"
        width="100.85407" height="39.0" strokeWidth="1.0"
        autoSized="false" controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#EA2218</strokeColor>
        <textColor>#EA2218</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a1643451c0a80007011f2184055f74af</URIString>
        <point1 x="105.92696" y="407.25"/>
        <point2 x="205.78104" y="445.25"/>
        <ID1 xsi:type="node">52</ID1>
        <ID2 xsi:type="node">70</ID2>
    </child>
    <child ID="72" label="occurs in" layerID="1" created="1428636657841"
        x="234.20438" y="406.75" width="45.0" height="39.0"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a1643469c0a80007011f21848dd8918d</URIString>
        <point1 x="243.80655" y="445.25"/>
        <point2 x="269.6022" y="407.25"/>
        <ID1 xsi:type="node">70</ID1>
        <ID2 xsi:type="node">55</ID2>
    </child>
    <child ID="74" label="is about" layerID="1" created="1428636715314"
        x="128.5" y="452.81183" width="50.131104" height="14.0"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#000000</strokeColor>
        <textColor>#4C4C4C</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a1643469c0a80007011f218490d291c9</URIString>
        <point1 x="129.0" y="460.72427"/>
        <point2 x="178.1311" y="458.8994"/>
        <ID1 xsi:type="node">46</ID1>
        <ID2 xsi:type="node">70</ID2>
    </child>
    <child ID="76" label="TNF" layerID="1" created="1428637099205"
        x="221.5" y="505.375" width="36.5" height="27.25"
        strokeWidth="1.0" autoSized="false" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a187dd57c0a80007011f21847898e66a</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="77" label="involved in postive&#xa;regulation of "
        layerID="1" created="1428637111100" x="193.311" y="467.75"
        width="89.0" height="38.125" strokeWidth="1.0" autoSized="false"
        controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#000000</strokeColor>
        <textColor>#4C4C4C</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a187dd57c0a80007011f21841302342b</URIString>
        <point1 x="238.92921" y="505.375"/>
        <point2 x="236.69278" y="468.25"/>
        <ID1 xsi:type="node">76</ID1>
        <ID2 xsi:type="node">70</ID2>
    </child>
    <child ID="78" label="Northern blotting&#xa;(OBI_0000860)"
        layerID="1" created="1428637419545" x="-148.0" y="378.25"
        width="102.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#ECFFD4</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a187dd57c0a80007011f218496cc31b3</URIString>
        <shape arcwidth="20.0" archeight="20.0" xsi:type="roundRect"/>
    </child>
    <child ID="80"
        label="conclusion drawn&#xa;from data&#xa;generated &#xa;by asay"
        layerID="1" created="1428637673950" x="-111.5" y="427.7329"
        width="105.0" height="56.0" strokeWidth="1.0" autoSized="false"
        controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#EA2218</strokeColor>
        <textColor>#EA2218</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a187dd58c0a80007011f21845151fab0</URIString>
        <point1 x="-7.0" y="458.9903"/>
        <point2 x="-111.0" y="452.47552"/>
        <ID1 xsi:type="node">46</ID1>
        <ID2 xsi:type="node">81</ID2>
    </child>
    <child ID="81" label="qRT-PCR &#xa;(OBI_0000911)" layerID="1"
        created="1428637678181" x="-206.0" y="430.5" width="95.0"
        height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#ECFFD4</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a187dd58c0a80007011f2184ee571acf</URIString>
        <shape arcwidth="20.0" archeight="20.0" xsi:type="roundRect"/>
    </child>
    <child ID="88" label="involved in &#xa;postive&#xa;regulation of "
        layerID="1" created="1428638651633" x="215.41412" y="256.80963"
        width="77.08589" height="42.0" strokeWidth="1.0"
        autoSized="false" controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#000000</strokeColor>
        <textColor>#4C4C4C</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a187dd58c0a80007011f2184694083bc</URIString>
        <point1 x="292.0" y="276.54477"/>
        <point2 x="215.91411" y="279.07446"/>
        <ID1 xsi:type="node">33</ID1>
        <ID2 xsi:type="node">41</ID2>
    </child>
    <child ID="89" label="upregulated miRNA&#xa; expression conclusion"
        layerID="1" created="1428639124828" x="-212.5" y="239.5"
        width="138.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a187dd58c0a80007011f2184fce4c29e</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="92"
        label="The miR-128 mimic decreased&#xa; UPF1 protein levels"
        layerID="1" created="1428684000321" x="-28.0" y="664.1875"
        width="182.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a4402eefc0a80007010085847d5bbfa6</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="93"
        label="miRNA downregulated target protein&#xa; expression conclusion"
        layerID="1" created="1428684023553" x="-264.25" y="663.1875"
        width="210.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a4402ef0c0a80007010085842fae2c46</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="94"
        label="miRNA mimic downregulates &#xa; target protein&#xa;expression conclusion"
        layerID="1" created="1428684054689" x="-164.75" y="730.5"
        width="175.0" height="53.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a4402ef0c0a8000701008584ec3b16fe</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="95" label="is_a" layerID="1" created="1428684088048"
        x="-27.397732" y="701.6875" width="54.796154" height="29.3125"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a4402ef1c0a800070100858472216417</URIString>
        <point1 x="26.898422" y="702.1875"/>
        <point2 x="-26.897732" y="730.5"/>
        <ID1 xsi:type="node">92</ID1>
        <ID2 xsi:type="node">94</ID2>
    </child>
    <child ID="96" label="is_a" layerID="1" created="1428684095960"
        x="-138.92462" y="700.6875" width="33.12864" height="30.3125"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a4402ef1c0a8000701008584ee755b12</URIString>
        <point1 x="-106.29598" y="730.5"/>
        <point2 x="-138.42462" y="701.1875"/>
        <ID1 xsi:type="node">94</ID1>
        <ID2 xsi:type="node">93</ID2>
    </child>
    <child ID="97" label="publication 21596314" layerID="1"
        created="1428684178999" x="53.25" y="730.5" width="130.0"
        height="23.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a4402ef2c0a800070100858435ed2624</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="98" label="part of" layerID="1" created="1428684186286"
        x="78.14785" y="701.6875" width="32.0" height="29.3125"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a4402ef2c0a800070100858487695958</URIString>
        <point1 x="80.84908" y="702.1875"/>
        <point2 x="107.44662" y="730.5"/>
        <ID1 xsi:type="node">92</ID1>
        <ID2 xsi:type="node">97</ID2>
    </child>
    <child ID="99" label="western blot analysis&#xa;(OBI_0000854)"
        layerID="1" created="1428684195031" x="-0.5" y="587.5"
        width="127.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#ECFFD4</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a4402ef3c0a80007010085849f5ca184</URIString>
        <shape arcwidth="20.0" archeight="20.0" xsi:type="roundRect"/>
    </child>
    <child ID="100"
        label="conclusion based on &#xa;data generated by asay"
        layerID="1" created="1428684260749" x="5.0" y="625.0"
        width="116.0" height="39.6875" strokeWidth="1.0"
        autoSized="false" controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#EA2218</strokeColor>
        <textColor>#EA2218</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a4402ef3c0a8000701008584434be306</URIString>
        <point1 x="63.0" y="664.1875"/>
        <point2 x="63.0" y="625.5"/>
        <ID1 xsi:type="node">92</ID1>
        <ID2 xsi:type="node">99</ID2>
    </child>
    <child ID="101" label="has &#xa;evaluant" layerID="1"
        created="1428684407035" x="113.7242" y="625.0"
        width="105.301674" height="39.6875" strokeWidth="1.0"
        autoSized="false" controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#EA2218</strokeColor>
        <textColor>#EA2218</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a4402ef4c0a800070100858467ae73d3</URIString>
        <point1 x="114.22419" y="625.5"/>
        <point2 x="218.52586" y="664.1875"/>
        <ID1 xsi:type="node">99</ID1>
        <ID2 xsi:type="node">102</ID2>
    </child>
    <child ID="102"
        label="mouse primary embryonic&#xa; neural stem cells (NSCs)"
        layerID="1" created="1428684411883" x="192.75" y="664.1875"
        width="154.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a4402ef5c0a8000701008584c63877ef</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="103" label="output data&#xa; is about" layerID="1"
        created="1428684482074" x="126.0" y="594.4032" width="70.75"
        height="28.0" strokeWidth="1.0" autoSized="false"
        controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#EA2218</strokeColor>
        <textColor>#EA2218</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a4402ef5c0a800070100858477097407</URIString>
        <point1 x="126.5" y="607.7285"/>
        <point2 x="196.25" y="609.07794"/>
        <ID1 xsi:type="node">99</ID1>
        <ID2 xsi:type="node">104</ID2>
    </child>
    <child ID="104" label="protein UPF1 expression" layerID="1"
        created="1428684521003" x="196.25" y="599.0" width="147.0"
        height="23.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#ECFFD4</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a4402ef6c0a80007010085847912aba4</URIString>
        <shape arcwidth="20.0" archeight="20.0" xsi:type="roundRect"/>
    </child>
    <child ID="105" label="occurs in" layerID="1"
        created="1428684548114" x="247.25" y="621.5" width="45.0"
        height="43.1875" strokeWidth="1.0" autoSized="false"
        controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a4402ef6c0a800070100858406171f44</URIString>
        <point1 x="269.75" y="622.0"/>
        <point2 x="269.75" y="664.1875"/>
        <ID1 xsi:type="node">104</ID1>
        <ID2 xsi:type="node">102</ID2>
    </child>
    <child ID="106" label="mouse " layerID="1" created="1428684565018"
        x="243.25" y="724.0" width="53.0" height="23.0"
        strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a4402ef6c0a800070100858457f90681</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="107" label="part of" layerID="1" created="1428684576970"
        x="253.75" y="701.6875" width="32.0" height="22.8125"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a4402ef7c0a8000701008584997f68cb</URIString>
        <point1 x="269.75" y="702.1875"/>
        <point2 x="269.75" y="724.0"/>
        <ID1 xsi:type="node">102</ID1>
        <ID2 xsi:type="node">106</ID2>
    </child>
    <child ID="108" label="Nonsense-mediated &#xa;decay (NMD)"
        layerID="1" created="1428684605265" x="205.75" y="768.875"
        width="128.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a4402ef7c0a8000701008584c719163f</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="109" label="has disposition" layerID="1"
        created="1428684623129" x="233.75" y="746.5" width="72.0"
        height="22.875" strokeWidth="1.0" autoSized="false"
        controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a4402ef7c0a8000701008584cf9bffca</URIString>
        <point1 x="269.75" y="747.0"/>
        <point2 x="269.75" y="768.875"/>
        <ID1 xsi:type="node">106</ID1>
        <ID2 xsi:type="node">108</ID2>
    </child>
    <child ID="110"
        label="conclusion based on data &#xa; generated by asay"
        layerID="1" created="1428685204010" x="352.66278" y="18.5"
        width="128.0" height="47.0" strokeWidth="1.0" autoSized="false"
        controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#EA2218</strokeColor>
        <textColor>#EA2218</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a44e73e4c0a80007010085844c059792</URIString>
        <point1 x="416.57364" y="65.0"/>
        <point2 x="416.75192" y="19.0"/>
        <ID1 xsi:type="node">8</ID1>
        <ID2 xsi:type="node">7</ID2>
    </child>
    <child ID="111" label="output data&#xa; is about" layerID="1"
        created="1428685238674" x="486.5" y="-3.5227356"
        width="63.571777" height="38.522766" strokeWidth="1.0"
        autoSized="false" controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#EA2218</strokeColor>
        <textColor>#EA2218</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a44e73e4c0a8000701008584fe104076</URIString>
        <point1 x="487.0" y="-3.0227356"/>
        <point2 x="549.5718" y="34.50003"/>
        <ID1 xsi:type="node">7</ID1>
        <ID2 xsi:type="node">10</ID2>
    </child>
    <child ID="112" label="has&#xa; evaluant" layerID="1"
        created="1428685354728" x="486.5" y="-58.862663" width="72.5"
        height="28.0" strokeWidth="1.0" autoSized="false"
        controlCount="0" arrowState="2" xsi:type="link">
        <strokeColor>#EA2218</strokeColor>
        <textColor>#EA2218</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a44e73e4c0a8000701008584ec11727e</URIString>
        <point1 x="487.0" y="-44.90909"/>
        <point2 x="558.5" y="-44.816235"/>
        <ID1 xsi:type="node">7</ID1>
        <ID2 xsi:type="node">9</ID2>
    </child>
    <child ID="113" label="miRNA " layerID="1" created="1428685483686"
        x="348.0" y="126.0" width="53.0" height="23.0" strokeWidth="1.0"
        autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a44e73e5c0a800070100858403c32d8a</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="114" label="target protein" layerID="1"
        created="1428685491958" x="408.0" y="126.0" width="83.0"
        height="23.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a44e73e5c0a800070100858418aec17d</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="115" label="is about" layerID="1" created="1428685509942"
        x="373.5561" y="102.50003" width="38.0" height="23.99997"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a44e73e5c0a80007010085846146c206</URIString>
        <point1 x="401.5841" y="103.00003"/>
        <point2 x="383.52805" y="126.0"/>
        <ID1 xsi:type="node">8</ID1>
        <ID2 xsi:type="node">113</ID2>
    </child>
    <child ID="116" label="is about" layerID="1" created="1428685516901"
        x="416.3131" y="102.5" width="38.0" height="24.0"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a44e73e5c0a800070100858470548015</URIString>
        <point1 x="428.21964" y="103.0"/>
        <point2 x="442.40656" y="126.0"/>
        <ID1 xsi:type="node">8</ID1>
        <ID2 xsi:type="node">114</ID2>
    </child>
    <child ID="124"
        label="miRNA traget gene mRNA&#xa; binding conclusion"
        layerID="1" created="1428685910986" x="165.1" y="131.20001"
        width="154.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a45447bdc0a800070100858458ca7be3</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="125" label="upregulated miRNA&#xa;expression conclusion"
        layerID="1" created="1428685944784" x="162.59998" y="-42.3"
        width="135.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a45447bdc0a8000701008584c4cdadb1</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="126"
        label="downegulated miRNA&#xa; expression conclusion"
        layerID="1" created="1428685946536" x="159.8" y="6.299999"
        width="138.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a45447bdc0a8000701008584fd58366c</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="127"
        label="upregulated target protein&#xa; expression conclusion"
        layerID="1" created="1428685949792" x="155.0" y="58.5"
        width="152.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a45447bdc0a80007010085849abc4fb8</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="128"
        label="downregulated target protein&#xa; expression conclusion"
        layerID="1" created="1428685951031" x="142.99998" y="94.1"
        width="168.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a45447bdc0a800070100858473914598</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="132" label="is_a" layerID="1" created="1428686050520"
        x="310.5" y="90.052765" width="42.0" height="14.0"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a45447bec0a8000701008584bb11639f</URIString>
        <point1 x="311.0" y="100.20078"/>
        <point2 x="352.0" y="93.90475"/>
        <ID1 xsi:type="node">128</ID1>
        <ID2 xsi:type="node">8</ID2>
    </child>
    <child ID="133" label="is_a" layerID="1" created="1428686059390"
        x="306.5" y="73.95148" width="46.0" height="14.0"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a45447bec0a8000701008584d460bc91</URIString>
        <point1 x="307.0" y="80.16307"/>
        <point2 x="352.0" y="81.73989"/>
        <ID1 xsi:type="node">127</ID1>
        <ID2 xsi:type="node">8</ID2>
    </child>
    <child ID="134" label="is_a" layerID="1" created="1428686068512"
        x="262.6065" y="-4.800003" width="121.38696" height="70.29999"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a45447bec0a8000701008584790917e7</URIString>
        <point1 x="263.1065" y="-4.300003"/>
        <point2 x="383.49347" y="64.999985"/>
        <ID1 xsi:type="node">125</ID1>
        <ID2 xsi:type="node">8</ID2>
    </child>
    <child ID="135" label="is_a" layerID="1" created="1428686075302"
        x="289.0547" y="43.800003" width="67.19061" height="21.7"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a45447bfc0a80007010085842379e211</URIString>
        <point1 x="289.5547" y="44.3"/>
        <point2 x="355.7453" y="65.0"/>
        <ID1 xsi:type="node">126</ID1>
        <ID2 xsi:type="node">8</ID2>
    </child>
    <child ID="138" label="is_a" layerID="1" created="1428686105886"
        x="293.77338" y="90.28917" width="58.726624" height="41.410843"
        strokeWidth="1.0" autoSized="false" controlCount="2"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#4C4C4C</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/a45447bfc0a80007010085841d51fcc8</URIString>
        <point1 x="294.27338" y="131.20001"/>
        <point2 x="352.0" y="90.78917"/>
        <ID1 xsi:type="node">124</ID1>
        <ID2 xsi:type="node">8</ID2>
        <ctrlPoint0 x="321.42947" y="121.310555" xsi:type="point"/>
        <ctrlPoint1 x="328.8483" y="93.22608" xsi:type="point"/>
    </child>
    <child ID="139" label="miRNA target&#xa;emperical conclusion"
        layerID="1" created="1428784904752" x="828.0" y="331.96716"
        width="129.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/aa5b715ac0a80007003f4b8733996832</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="140" label="experimental evidence role" layerID="1"
        created="1428784914758" x="612.85004" y="299.26715"
        width="158.0" height="23.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/aa5b715bc0a80007003f4b87ff64201d</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="141" label="has role" layerID="1" created="1428784935861"
        x="748.7499" y="321.76715" width="79.75012" height="16.777496"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/aa5b715bc0a80007003f4b872738cc55</URIString>
        <point1 x="828.0" y="338.04465"/>
        <point2 x="749.2499" y="322.26715"/>
        <ID1 xsi:type="node">139</ID1>
        <ID2 xsi:type="node">140</ID2>
    </child>
    <child ID="142"
        label="conclusion suggested by&#xa;software algorithm"
        layerID="1" created="1428787053325" x="630.5" y="443.96716"
        width="148.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/aa5b715cc0a80007003f4b8715d47a74</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="143"
        label="software predicted &#xa;miRNA target conclusion"
        layerID="1" created="1428787102659" x="817.5" y="386.96716"
        width="147.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/aa5b715cc0a80007003f4b87a9438af7</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="144" label="is_a" layerID="1" created="1428787125555"
        x="766.1667" y="424.46716" width="63.166626" height="20.0"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/aa5b715dc0a80007003f4b8775e05fed</URIString>
        <point1 x="828.8333" y="424.96716"/>
        <point2 x="766.6667" y="443.96716"/>
        <ID1 xsi:type="node">143</ID1>
        <ID2 xsi:type="node">142</ID2>
    </child>
    <child ID="145" label="automatically asserted&#xa;evidence role"
        layerID="1" created="1428787168779" x="616.25" y="387.46716"
        width="135.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/aa5b715dc0a80007003f4b8721064eea</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="146" label="has role" layerID="1" created="1428787188843"
        x="750.75" y="399.2244" width="67.25" height="14.0"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/aa5b715dc0a80007003f4b87eda580a5</URIString>
        <point1 x="817.5" y="406.14447"/>
        <point2 x="751.25" y="406.30432"/>
        <ID1 xsi:type="node">143</ID1>
        <ID2 xsi:type="node">145</ID2>
    </child>
    <child ID="147" label=" evidence role" layerID="1"
        created="1428787198634" x="645.75" y="344.66718" width="87.0"
        height="23.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/aa5b715dc0a80007003f4b877ee742f4</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="148" label="is_a" layerID="1" created="1428787209867"
        x="680.55005" y="321.76758" width="20.0" height="23.399414"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/aa5b715ec0a80007003f4b87b194f459</URIString>
        <point1 x="691.19147" y="322.26758"/>
        <point2 x="689.9086" y="344.667"/>
        <ID1 xsi:type="node">140</ID1>
        <ID2 xsi:type="node">147</ID2>
    </child>
    <child ID="149" label="is_a" layerID="1" created="1428787226286"
        x="676.91003" y="367.1665" width="20.0" height="20.800781"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/aa5b715ec0a80007003f4b878b8455b4</URIString>
        <point1 x="685.8275" y="387.4673"/>
        <point2 x="687.9926" y="367.6665"/>
        <ID1 xsi:type="node">145</ID1>
        <ID2 xsi:type="node">147</ID2>
    </child>
    <child ID="150" label="miRNA target&#xa;experimental evidence"
        layerID="1" created="1428789610764" x="991.0" y="330.96716"
        width="134.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/aa87af17c0a80007003f4b8742bcb043</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="151" label="is_a" layerID="1" created="1428789621988"
        x="956.5" y="343.47473" width="35.0" height="14.0"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/aa87af17c0a80007003f4b87b75bd9a5</URIString>
        <point1 x="957.0" y="350.57745"/>
        <point2 x="991.0" y="350.372"/>
        <ID1 xsi:type="node">139</ID1>
        <ID2 xsi:type="node">150</ID2>
    </child>
    <child ID="152"
        label="computationally asserted &#xa;miRNA target evidence"
        layerID="1" created="1428789646645" x="994.0" y="387.96716"
        width="152.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/aa87af17c0a80007003f4b875acc70f4</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="153" label="is_a" layerID="1" created="1428789678107"
        x="964.0" y="399.46017" width="30.5" height="14.0"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/aa87af17c0a80007003f4b87b21abc7f</URIString>
        <point1 x="964.5" y="406.37778"/>
        <point2 x="994.0" y="406.54257"/>
        <ID1 xsi:type="node">143</ID1>
        <ID2 xsi:type="node">152</ID2>
    </child>
    <child ID="154" label="experimental evidence&#xa;(ECO_0000006)"
        layerID="1" created="1428809182060" x="986.0" y="265.96716"
        width="134.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abab018bc0a80007003f4b8726c0f89f</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="155" label="is_a" layerID="1" created="1428809240142"
        x="1045.5" y="303.4668" width="20.0" height="28.0"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abab018bc0a80007003f4b87ecb671db</URIString>
        <point1 x="1056.5385" y="330.9668"/>
        <point2 x="1054.4615" y="303.9668"/>
        <ID1 xsi:type="node">150</ID1>
        <ID2 xsi:type="node">154</ID2>
    </child>
    <child ID="156" label="bioinformatics evidence&#xa;(ECO_???)"
        layerID="1" created="1428810209202" x="1073.5" y="450.96716"
        width="141.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcdbc0a80007003f4b878f38cc3e</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="157" label="is_a" layerID="1" created="1428810227874"
        x="1091.8175" y="425.46722" width="30.36499" height="25.999939"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcdbc0a80007003f4b87be478c99</URIString>
        <point1 x="1092.3175" y="425.96722"/>
        <point2 x="1121.6825" y="450.96716"/>
        <ID1 xsi:type="node">152</ID1>
        <ID2 xsi:type="node">156</ID2>
    </child>
    <child ID="158" label="predicted miRNA target" layerID="1"
        created="1428810283472" x="602.0" y="501.96716" width="226.0"
        height="73.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcdbc0a80007003f4b87decce50b</URIString>
        <child ID="161"
            label="'molecular entity' and 'miRNA target based &#xa;      on' some 'computationally asserted miRNAtarget evidence'"
            created="1428810344521" x="5.0" y="23.0" width="216.0"
            height="44.0" strokeWidth="0.0" autoSized="false" xsi:type="text">
            <strokeColor>#404040</strokeColor>
            <textColor>#000000</textColor>
            <font>Arial-plain-10</font>
            <URIString>http://vue.tufts.edu/rdf/resource/abdbdcdbc0a80007003f4b87e22971de</URIString>
            <richText>&lt;html&gt;
  &lt;head color="#000000" style="color: #000000"&gt;
    &lt;style type="text/css"&gt;
      &lt;!--
        body { color: #000000; margin-right: 0px; font-size: 12; font-family: Arial; margin-top: 0px; margin-bottom: 0px; margin-left: 0px }
        ol { vertical-align: middle; font-size: 12; font-family: Arial; margin-top: 6; list-style-position: outside; margin-left: 30 }
        p { color: #000000; margin-right: 0; margin-top: 0; margin-bottom: 0; margin-left: 0 }
        ul { vertical-align: middle; font-size: 12; font-family: Arial; margin-top: 6; margin-left: 30; list-style-position: outside }
      --&gt;
    &lt;/style&gt;
    
  &lt;/head&gt;
  &lt;body&gt;
    &lt;p color="#000000" style="color: #000000"&gt;
      &lt;font style="font-size:10;"&gt;'molecular entity' and 'miRNA target based 
      on' some 'computationally asserted miRNAtarget evidence'&lt;/font&gt;
    &lt;/p&gt;
  &lt;/body&gt;
&lt;/html&gt;
</richText>
            <label>'molecular entity' and 'miRNA target based 
      on' some 'computationally asserted miRNAtarget evidence'</label>
        </child>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="159" label="experimentally validated miRNA target"
        layerID="1" created="1428810303729" x="604.5" y="604.46716"
        width="226.0" height="70.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcdcc0a80007003f4b87acba0fcf</URIString>
        <child ID="162"
            label="'predicted miRNA target' and 'miRNA target &#xa;      based on' some 'miRNA target experimental evident'"
            created="1428810345735" x="5.0" y="23.0" width="216.0"
            height="41.0" strokeWidth="0.0" autoSized="false" xsi:type="text">
            <strokeColor>#404040</strokeColor>
            <textColor>#000000</textColor>
            <font>Arial-plain-10</font>
            <URIString>http://vue.tufts.edu/rdf/resource/abdbdcdcc0a80007003f4b871fa1b5bc</URIString>
            <richText>&lt;html&gt;
  &lt;head color="#000000" style="color: #000000"&gt;
    &lt;style type="text/css"&gt;
      &lt;!--
        body { color: #000000; margin-right: 0px; font-size: 12; font-family: Arial; margin-top: 0px; margin-bottom: 0px; margin-left: 0px }
        ol { vertical-align: middle; font-size: 12; font-family: Arial; margin-top: 6; list-style-position: outside; margin-left: 30 }
        p { color: #000000; margin-right: 0; margin-top: 0; margin-bottom: 0; margin-left: 0 }
        ul { vertical-align: middle; font-size: 12; font-family: Arial; margin-top: 6; margin-left: 30; list-style-position: outside }
      --&gt;
    &lt;/style&gt;
    
  &lt;/head&gt;
  &lt;body&gt;
    &lt;p color="#000000" style="color: #000000"&gt;
      &lt;font style="font-size:10;"&gt;'predicted miRNA target' and 'miRNA target 
      based on' some 'miRNA target experimental evident'&lt;/font&gt;
    &lt;/p&gt;
  &lt;/body&gt;
&lt;/html&gt;
</richText>
            <label>'predicted miRNA target' and 'miRNA target 
      based on' some 'miRNA target experimental evident'</label>
        </child>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="163" label="predicted miRNA target" layerID="1"
        created="1428810663020" x="823.5" y="454.46716" width="138.0"
        height="23.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcddc0a80007003f4b8787fa8a7c</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="164" label="is about" layerID="1" created="1428810673675"
        x="872.84375" y="424.46875" width="38.0" height="30.5"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#000000</strokeColor>
        <textColor>#4C4C4C</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcddc0a80007003f4b87a89700f6</URIString>
        <point1 x="891.475" y="424.96875"/>
        <point2 x="892.2126" y="454.46875"/>
        <ID1 xsi:type="node">143</ID1>
        <ID2 xsi:type="node">163</ID2>
    </child>
    <child ID="165" label="miRNA target based on" layerID="1"
        created="1428810698729" x="939.6438" y="425.46716"
        width="116.88092" height="29.5" strokeWidth="1.0"
        autoSized="false" controlCount="2" arrowState="2" xsi:type="link">
        <strokeColor>#000000</strokeColor>
        <textColor>#4C4C4C</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcddc0a80007003f4b878a796cf1</URIString>
        <point1 x="940.1438" y="454.46716"/>
        <point2 x="1042.1703" y="425.96716"/>
        <ID1 xsi:type="node">163</ID1>
        <ID2 xsi:type="node">152</ID2>
        <ctrlPoint0 x="997.9492" y="440.51437" xsi:type="point"/>
        <ctrlPoint1 x="1010.67865" y="447.4672" xsi:type="point"/>
    </child>
    <child ID="166" label="experimentally validated&#xa; miRNA target"
        layerID="1" created="1428811025111" x="826.5" y="261.46716"
        width="142.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcddc0a80007003f4b876baa430b</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="167" label="is about" layerID="1" created="1428811055040"
        x="876.0" y="298.9668" width="38.0" height="33.5"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#000000</strokeColor>
        <textColor>#4C4C4C</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcddc0a80007003f4b876a438dbc</URIString>
        <point1 x="893.8475" y="331.9668"/>
        <point2 x="896.15247" y="299.4668"/>
        <ID1 xsi:type="node">139</ID1>
        <ID2 xsi:type="node">166</ID2>
    </child>
    <child ID="168" label="miRNA target based on" layerID="1"
        created="1428811121463" x="918.41693" y="298.46716"
        width="111.0" height="33.0" strokeWidth="1.0" autoSized="false"
        controlCount="2" arrowState="2" xsi:type="link">
        <strokeColor>#000000</strokeColor>
        <textColor>#4C4C4C</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcddc0a80007003f4b872e6c6a4a</URIString>
        <point1 x="924.5" y="298.96716"/>
        <point2 x="1008.5234" y="330.96716"/>
        <ID2 xsi:type="node">150</ID2>
        <ctrlPoint0 x="1018.7546" y="333.21628" xsi:type="point"/>
        <ctrlPoint1 x="934.01605" y="302.3549" xsi:type="point"/>
    </child>
    <child ID="169" label="level 1 validated miRNA target" layerID="1"
        created="1428811250365" x="888.5" y="529.46716" width="174.0"
        height="23.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcddc0a80007003f4b871d5e245b</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="170" label="level 2 validated miRNA target" layerID="1"
        created="1428811318212" x="895.5" y="563.46716" width="174.0"
        height="23.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcddc0a80007003f4b871f3d9a89</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="171" label="level 3 validated miRNA target" layerID="1"
        created="1428811324972" x="899.5" y="604.46716" width="174.0"
        height="23.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcdec0a80007003f4b8783ecf541</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="172" label="level 4 validated miRNA target" layerID="1"
        created="1428811331308" x="900.5" y="662.46716" width="174.0"
        height="23.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcdec0a80007003f4b87299d7b63</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="174" label="is_a" layerID="1" created="1428811481017"
        x="830.0" y="546.66077" width="59.0" height="70.513916"
        strokeWidth="1.0" autoSized="false" controlCount="2"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcdec0a80007003f4b87893b8db0</URIString>
        <point1 x="888.5" y="547.16077"/>
        <point2 x="830.5" y="616.6747"/>
        <ID1 xsi:type="node">169</ID1>
        <ID2 xsi:type="node">159</ID2>
        <ctrlPoint0 x="864.90594" y="548.84045" xsi:type="point"/>
        <ctrlPoint1 x="861.502" y="610.4215" xsi:type="point"/>
    </child>
    <child ID="175" label="is_a" layerID="1" created="1428811490761"
        x="830.0" y="579.3631" width="66.0" height="51.072876"
        strokeWidth="1.0" autoSized="false" controlCount="2"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcdec0a80007003f4b8771e1eb96</URIString>
        <point1 x="895.5" y="579.8631"/>
        <point2 x="830.5" y="629.936"/>
        <ID1 xsi:type="node">170</ID1>
        <ID2 xsi:type="node">159</ID2>
        <ctrlPoint0 x="883.47797" y="580.5396" xsi:type="point"/>
        <ctrlPoint1 x="864.5003" y="627.0682" xsi:type="point"/>
    </child>
    <child ID="176" label="is_a" layerID="1" created="1428811509945"
        x="830.0" y="623.4071" width="70.0" height="15.84375"
        strokeWidth="1.0" autoSized="false" controlCount="2"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcdec0a80007003f4b87867a1e25</URIString>
        <point1 x="899.5" y="623.9071"/>
        <point2 x="830.5" y="638.6927"/>
        <ID1 xsi:type="node">171</ID1>
        <ID2 xsi:type="node">159</ID2>
        <ctrlPoint0 x="869.6054" y="626.63544" xsi:type="point"/>
        <ctrlPoint1 x="858.5627" y="638.50037" xsi:type="point"/>
    </child>
    <child ID="177" label="is_a" layerID="1" created="1428811515288"
        x="830.0" y="649.00055" width="71.0" height="24.645325"
        strokeWidth="1.0" autoSized="false" controlCount="2"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcdfc0a80007003f4b87ad24d635</URIString>
        <point1 x="900.5" y="673.1459"/>
        <point2 x="830.5" y="649.50055"/>
        <ID1 xsi:type="node">172</ID1>
        <ID2 xsi:type="node">159</ID2>
        <ctrlPoint0 x="882.50555" y="672.97595" xsi:type="point"/>
        <ctrlPoint1 x="856.74945" y="651.8313" xsi:type="point"/>
    </child>
    <child ID="180"
        label="miRNA target protein &#xa;co-expression conclusion"
        layerID="1" created="1428811869749" x="168.5" y="-94.832825"
        width="152.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcdfc0a80007003f4b8775333760</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="181" label="is_a" layerID="1" created="1428811900044"
        x="257.86673" y="-57.332825" width="94.63327" height="132.22964"
        strokeWidth="1.0" autoSized="false" controlCount="2"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#4C4C4C</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcdfc0a80007003f4b87e5cf0539</URIString>
        <point1 x="258.36673" y="-56.832825"/>
        <point2 x="352.0" y="74.39682"/>
        <ID1 xsi:type="node">180</ID1>
        <ID2 xsi:type="node">8</ID2>
        <ctrlPoint0 x="308.06567" y="11.264041" xsi:type="point"/>
        <ctrlPoint1 x="329.6288" y="71.066055" xsi:type="point"/>
    </child>
    <child ID="183" layerID="1" created="1428812027926" x="1103.5"
        y="774.96716" width="300.0" height="55.0" strokeWidth="0.0"
        autoSized="false" xsi:type="text">
        <strokeColor>#404040</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-10</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdcdfc0a80007003f4b871f96ea93</URIString>
        <richText>&lt;html&gt;
  &lt;head&gt;
    &lt;style type="text/css"&gt;
      &lt;!--
        body { color: #000000; margin-right: 0px; font-size: 12; font-family: Arial; margin-top: 0px; margin-bottom: 0px; margin-left: 0px }
        ol { vertical-align: middle; font-size: 12; font-family: Arial; margin-top: 6; list-style-position: outside; margin-left: 30 }
        p { color: #000000; margin-right: 0; margin-top: 0; margin-bottom: 0; margin-left: 0 }
        ul { vertical-align: middle; font-size: 12; font-family: Arial; margin-top: 6; margin-left: 30; list-style-position: outside }
      --&gt;
    &lt;/style&gt;
    
  &lt;/head&gt;
  &lt;body&gt;
    &lt;p&gt;
      
    &lt;/p&gt;
  &lt;/body&gt;
&lt;/html&gt;
</richText>
    </child>
    <child ID="188" label=" miRNA target  protein&#xa;binding evidence"
        layerID="1" created="1428812271152" x="1197.698" y="205.36713"
        width="131.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdce0c0a80007003f4b87fbc25dd8</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="189"
        label=" miRNA target protein&#xa;co-expression evidence"
        layerID="1" created="1428812314871" x="1197.198" y="255.36731"
        width="141.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdce0c0a80007003f4b8788b22c7a</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="190"
        label=" miRNA down regulating target&#xa;protein expression evidence"
        layerID="1" created="1428812333863" x="1194.198" y="303.3673"
        width="178.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdce0c0a80007003f4b8719489cb5</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="192"
        label="evidence of miRNA regulating &#xa;downstream biological function"
        layerID="1" created="1428812401871" x="1197.098" y="349.3673"
        width="182.0" height="38.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abdbdce1c0a80007003f4b87a7c2f530</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="193" label="is_a" layerID="1" created="1428812891672"
        x="1124.5" y="219.63466" width="73.698" height="114.58263"
        strokeWidth="1.0" autoSized="false" controlCount="2"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abeb7616c0a80007003f4b875f7f1b04</URIString>
        <point1 x="1197.698" y="220.13466"/>
        <point2 x="1125.0" y="333.7173"/>
        <ID1 xsi:type="node">188</ID1>
        <ID2 xsi:type="node">150</ID2>
        <ctrlPoint0 x="1175.502" y="218.70041" xsi:type="point"/>
        <ctrlPoint1 x="1143.4673" y="329.23834" xsi:type="point"/>
    </child>
    <child ID="200" label="is_a" layerID="1" created="1428813016695"
        x="1124.5" y="277.0312" width="73.198" height="64.65338"
        strokeWidth="1.0" autoSized="false" controlCount="2"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abeb7616c0a80007003f4b87745c22aa</URIString>
        <point1 x="1197.198" y="277.5312"/>
        <point2 x="1125.0" y="341.18457"/>
        <ID1 xsi:type="node">189</ID1>
        <ID2 xsi:type="node">150</ID2>
        <ctrlPoint0 x="1177.1538" y="278.4307" xsi:type="point"/>
        <ctrlPoint1 x="1139.7427" y="339.25204" xsi:type="point"/>
    </child>
    <child ID="201" label="is_a" layerID="1" created="1428813041615"
        x="1124.5" y="324.71878" width="70.198" height="23.772247"
        strokeWidth="1.0" autoSized="false" controlCount="2"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abeb7616c0a80007003f4b87ada2db66</URIString>
        <point1 x="1194.198" y="325.21878"/>
        <point2 x="1125.0" y="347.99103"/>
        <ID1 xsi:type="node">190</ID1>
        <ID2 xsi:type="node">150</ID2>
        <ctrlPoint0 x="1161.5072" y="326.26614" xsi:type="point"/>
        <ctrlPoint1 x="1152.3221" y="347.18515" xsi:type="point"/>
    </child>
    <child ID="203" label="is_a" layerID="1" created="1428813088206"
        x="1124.5" y="358.02292" width="73.09802" height="14.0"
        strokeWidth="1.0" autoSized="false" controlCount="2"
        arrowState="2" xsi:type="link">
        <strokeColor>#404040</strokeColor>
        <textColor>#404040</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abeb7617c0a80007003f4b874cbb8969</URIString>
        <point1 x="1197.098" y="364.8858"/>
        <point2 x="1125.0" y="362.3448"/>
        <ID1 xsi:type="node">192</ID1>
        <ID2 xsi:type="node">150</ID2>
        <ctrlPoint0 x="1163.1431" y="363.58673" xsi:type="point"/>
        <ctrlPoint1 x="1152.3503" y="367.3975" xsi:type="point"/>
    </child>
    <child ID="204"
        label="'predicted miRNA target' and --- 'miRNA target protein binding evidence"
        layerID="1" created="1428813998865" x="1061.5" y="525.96716"
        width="349.0" height="21.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#C6E8FF</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-10</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abf704e7c0a80007003f4b87c08984c8</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="205"
        label="('predicted miRNA target' and --('miRNA target protein binding evidence' ) &#xa;and ('predicted miRNA target and  ('miRNA target protein co-expression evidence'))"
        layerID="1" created="1428814050689" x="1065.0" y="558.46716"
        width="401.0" height="34.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#C6E8FF</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-10</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abf704e8c0a80007003f4b87cfd39165</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="206"
        label="('predicted miRNA target' and --('miRNA target protein binding evidence' )&#xa;and ('predicted miRNA target and ('miRNA target protein co-expression evidence'))&#xa;and ('predicted miRNA target' and --'miRNA downregulating target protein expression evidence'"
        layerID="1" created="1428814117330" x="1067.0" y="600.96716"
        width="458.0" height="47.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#C6E8FF</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-10</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abf704e8c0a80007003f4b877fd17a97</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="209"
        label="('predicted miRNA target' and --('miRNA target protein binding evidence' ) &#xa;and ('predicted miRNA target and ('miRNA target protein co-expression evidence'))&#xa; and ('predicted miRNA target' and --'miRNA downregulatestarget protein expression evidence')"
        layerID="1" created="1428814204712" x="1066.5" y="658.46716"
        width="456.0" height="47.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#C6E8FF</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-10</font>
        <URIString>http://vue.tufts.edu/rdf/resource/abf704e8c0a80007003f4b87d2101789</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="210" label="miRNA target" layerID="1"
        created="1428816074018" x="604.4" y="702.46716" width="201.0"
        height="58.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/ac1711d0c0a80007003f4b87066d97c5</URIString>
        <child ID="211"
            label="'molecular entity' and 'miRNA target based &#xa;      on' some 'miRNA target evidence'"
            created="1428816074019" x="5.0" y="23.0" width="191.0"
            height="29.0" strokeWidth="0.0" autoSized="false" xsi:type="text">
            <strokeColor>#404040</strokeColor>
            <textColor>#000000</textColor>
            <font>Arial-plain-10</font>
            <URIString>http://vue.tufts.edu/rdf/resource/ac1711d0c0a80007003f4b879afde037</URIString>
            <richText>&lt;html&gt;
  &lt;head color="#000000" style="color: #000000"&gt;
    &lt;style type="text/css"&gt;
      &lt;!--
        body { color: #000000; margin-right: 0px; font-size: 12; font-family: Arial; margin-top: 0px; margin-bottom: 0px; margin-left: 0px }
        ol { vertical-align: middle; font-size: 12; font-family: Arial; margin-top: 6; list-style-position: outside; margin-left: 30 }
        p { color: #000000; margin-right: 0; margin-top: 0; margin-bottom: 0; margin-left: 0 }
        ul { vertical-align: middle; font-size: 12; font-family: Arial; margin-top: 6; margin-left: 30; list-style-position: outside }
      --&gt;
    &lt;/style&gt;
    
  &lt;/head&gt;
  &lt;body&gt;
    &lt;p color="#000000" style="color: #000000"&gt;
      &lt;font style="font-size:10;"&gt;'molecular entity' and 'miRNA target based 
      on' some 'miRNA target evidence'&lt;/font&gt;
    &lt;/p&gt;
  &lt;/body&gt;
&lt;/html&gt;
</richText>
            <label>'molecular entity' and 'miRNA target based 
      on' some 'miRNA target evidence'</label>
        </child>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="214" label="publication" layerID="1"
        created="1428968278608" x="505.5" y="127.0" width="71.0"
        height="23.0" strokeWidth="1.0" autoSized="true" xsi:type="node">
        <fillColor>#F4F5E9</fillColor>
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-12</font>
        <URIString>http://vue.tufts.edu/rdf/resource/b525fac8c0a8000701b38cdfc650dbfc</URIString>
        <shape xsi:type="rectangle"/>
    </child>
    <child ID="215" label="part of" layerID="1" created="1428968291056"
        x="459.4037" y="102.5" width="55.825714" height="25.0"
        strokeWidth="1.0" autoSized="false" controlCount="0"
        arrowState="2" xsi:type="link">
        <strokeColor>#000000</strokeColor>
        <textColor>#000000</textColor>
        <font>Arial-plain-11</font>
        <URIString>http://vue.tufts.edu/rdf/resource/b525fac9c0a8000701b38cdf332947d5</URIString>
        <point1 x="459.90366" y="103.0"/>
        <point2 x="514.7294" y="127.0"/>
        <ID1 xsi:type="node">8</ID1>
        <ID2 xsi:type="node">214</ID2>
    </child>
    <layer ID="1" label="Layer 1" created="1428592062152" x="0.0"
        y="0.0" width="1.4E-45" height="1.4E-45" strokeWidth="0.0" autoSized="false">
        <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdfdc0a80007011f218416513148</URIString>
    </layer>
    <userZoom>1.25</userZoom>
    <userOrigin x="-455.25" y="-151.875"/>
    <presentationBackground>#202020</presentationBackground>
    <PathwayList currentPathway="0" revealerIndex="-1">
        <pathway ID="0" label="Untitled Pathway" created="1428592062147"
            x="0.0" y="0.0" width="1.4E-45" height="1.4E-45"
            strokeWidth="0.0" autoSized="false" currentIndex="0" open="true">
            <strokeColor>#B3993333</strokeColor>
            <textColor>#000000</textColor>
            <font>SansSerif-plain-14</font>
            <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdfec0a80007011f2184ecc92ee1</URIString>
            <masterSlide ID="2" created="1428592062169" x="0.0" y="0.0"
                width="800.0" height="600.0" locked="true"
                strokeWidth="0.0" autoSized="false">
                <fillColor>#000000</fillColor>
                <strokeColor>#404040</strokeColor>
                <textColor>#000000</textColor>
                <font>SansSerif-plain-14</font>
                <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdfec0a80007011f2184fa077773</URIString>
                <titleStyle ID="3" label="Header"
                    created="1428592062436" x="335.5" y="172.5"
                    width="129.0" height="55.0" strokeWidth="0.0"
                    autoSized="true" isStyle="true" xsi:type="node">
                    <strokeColor>#404040</strokeColor>
                    <textColor>#FFFFFF</textColor>
                    <font>Gill Sans-plain-36</font>
                    <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdffc0a80007011f21845ec33353</URIString>
                    <shape xsi:type="rectangle"/>
                </titleStyle>
                <textStyle ID="4" label="Slide Text"
                    created="1428592062437" x="346.5" y="281.5"
                    width="107.0" height="37.0" strokeWidth="0.0"
                    autoSized="true" isStyle="true" xsi:type="node">
                    <strokeColor>#404040</strokeColor>
                    <textColor>#FFFFFF</textColor>
                    <font>Gill Sans-plain-22</font>
                    <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdffc0a80007011f218428f6ce0c</URIString>
                    <shape xsi:type="rectangle"/>
                </textStyle>
                <linkStyle ID="5" label="Links" created="1428592062439"
                    x="373.5" y="384.0" width="53.0" height="32.0"
                    strokeWidth="0.0" autoSized="true" isStyle="true" xsi:type="node">
                    <strokeColor>#404040</strokeColor>
                    <textColor>#B3BFE3</textColor>
                    <font>Gill Sans-plain-18</font>
                    <URIString>http://vue.tufts.edu/rdf/resource/9ed8cdffc0a80007011f2184e102862e</URIString>
                    <shape xsi:type="rectangle"/>
                </linkStyle>
            </masterSlide>
        </pathway>
    </PathwayList>
    <date>2015-04-09</date>
    <modelVersion>6</modelVersion>
    <saveLocation>C:\Users\yuln\Dropbox\miragingdb\modeling</saveLocation>
    <saveFile>C:\Users\yuln\Dropbox\miragingdb\modeling\evidence and assay-all.vue</saveFile>
</LW-MAP>
